process.env.PORT = 4030;
process.env.SERVER_NAME = "db-design";
process.env.CORS_ORIGINS = "https://example.com";
process.env.ACCESS_TOKEN_SECRET = "your_access_token_secret";
process.env.LOGGER_URL = "https://example.com";
process.env.KAFKA_BROKER = "broker";
process.env.KAFKA_CLIENT_ID = "client id";
process.env.DB_URL = "db-url";
process.env.NODE_ENV = "test";
